import{useEffect,useMemo,useState}from'react';
import{Bell,UserRound,AlertTriangle,Clock3,Check,ChevronRight,Users,Copy,ClipboardList,Settings,House,Pill,Volume2,Download,Upload,Trash2,Pause,Play,PenLine,X,CalendarClock}from'lucide-react';

type Role='patient'|'caregiver';type Unit='min'|'hour'|'day';
type Med={id:string;name:string;type:string;interval:number;unit:Unit;start:string|null;paused:boolean;relatedId:string|null;offset:number;note:string};
type Event={id:string;patientId:string;medId:string;medName?:string;at:string;by:string;kind:'used'|'administered';scheduledAt:string|null};
type User={id:string;name:string;email:string;password:string;role:Role;onboardingCompleted:boolean;patientId:string|null;shareCode:string|null};
type Store={version:string;users:User[];patients:{id:string;name:string}[];medications:Record<string,Med[]>;events:Event[];settings:{sound:boolean;notifications:boolean}};
const KEY='cm-v11-store',SESSION='cm-v11-session',CHANNEL='cm-v11-realtime';const uid=()=>crypto.randomUUID();
const seed=():Med[]=>[
{id:'med-pred',name:'Acetato de prednisolona',type:'Colírio',interval:2,unit:'hour',start:null,paused:false,relatedId:null,offset:0,note:''},
{id:'med-moxi',name:'Cloridrato de moxifloxacino',type:'Colírio',interval:3,unit:'hour',start:null,paused:false,relatedId:null,offset:0,note:''},
{id:'med-dorz',name:'Cloridrato de dorzolamida',type:'Colírio',interval:12,unit:'hour',start:null,paused:false,relatedId:null,offset:0,note:''},
{id:'med-brim',name:'Tartarato de brimonidina',type:'Colírio',interval:12,unit:'hour',start:null,paused:false,relatedId:'med-dorz',offset:7,note:''}];
async function load():Promise<Store>{const raw=localStorage.getItem(KEY);if(raw)return JSON.parse(raw);const[users,meds,patients,settings]=await Promise.all([fetch('/data/users.json').then(r=>r.json()),fetch('/data/medications.json').then(r=>r.json()),fetch('/data/patients.json').then(r=>r.json()).catch(()=>({patients:[]})),fetch('/data/settings.json').then(r=>r.json()).catch(()=>({settings:{sound:true,notifications:false}}))]);const x:Store={version:'1.1.0',users:(users.users||[]).map((u:any)=>({...u,patientId:u.role==='patient'?(u.patientId||u.id):'patient-demo',shareCode:u.role==='patient'?(u.shareCode||'DEMO-1234'):null})),patients:patients.patients?.length?patients.patients:[{id:'patient-demo',name:'Paciente Demo'}],medications:{},events:[],settings:settings.settings||{sound:true,notifications:false}};x.medications['patient-demo']=(meds.medications||seed()).map((m:any)=>({...m,unit:m.unit==='minutes'?'min':m.unit==='hours'?'hour':m.unit||'hour',start:null,paused:false,relatedId:m.relatedId||null,offset:m.offsetMinutes??m.offset??0,note:m.note||''}));localStorage.setItem(KEY,JSON.stringify(x));return x}
function save(x:Store){localStorage.setItem(KEY,JSON.stringify(x));try{const c=new BroadcastChannel(CHANNEL);c.postMessage(Date.now());c.close()}catch{}}
const step=(m:Med)=>m.interval*(m.unit==='min'?60000:m.unit==='hour'?3600000:86400000);
function baseTime(m:Med,meds:Med[]){let t=m.start?Date.parse(m.start):NaN;if(m.relatedId){const r=meds.find(a=>a.id===m.relatedId);if(r?.start)t=Date.parse(r.start)+m.offset*60000}return t}
function lastConfirmed(m:Med,events:Event[]){const xs=events.filter(e=>e.medId===m.id&&e.scheduledAt).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));return xs.length?Date.parse(xs[xs.length-1].at):null}
function pendingDose(m:Med,meds:Med[],events:Event[]){if(m.paused||m.interval<=0)return null;const last=lastConfirmed(m,events);if(last!==null)return last+step(m);const t=baseTime(m,meds);return Number.isFinite(t)?t:null}
const clock=(t:number)=>new Date(t).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});const date=(t:number)=>new Date(t).toLocaleDateString('pt-BR');
const remain=(t:number,n:number)=>{const x=t-n;if(x<=0){const y=Math.max(0,-x),h=Math.floor(y/3600000),m=Math.floor(y%3600000/60000);return h?`Atrasado ${h}h ${m}min`:m?`Atrasado ${m}min`:'Atrasado agora'}const h=Math.floor(x/3600000),m=Math.floor(x%3600000/60000);return x<10000?'Agora':h?`Em ${h}h ${m}min`:m?`Em ${m}min`:`Em ${Math.floor(x/1000)}s`};
function alarmSound(){try{const A=window.AudioContext||(window as any).webkitAudioContext,c=new A();[0,280,560,840,1120,1400].forEach(d=>setTimeout(()=>{const o=c.createOscillator(),g=c.createGain();o.type='square';o.frequency.value=880;g.gain.value=.1;o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>o.stop(),230)},d));setTimeout(()=>c.close(),1700)}catch{}}
function Auth({onLogin}:{onLogin:(u:User)=>void}){const[reg,setReg]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[err,setErr]=useState('');async function submit(){const d=await load();if(reg){if(!name.trim()||!email.trim()||pass.length<6)return setErr('Preencha os campos. A senha precisa ter 6 caracteres.');if(d.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return setErr('E-mail já cadastrado.');const id=uid(),u:User={id,name:name.trim(),email:email.trim(),password:pass,role:'patient',onboardingCompleted:false,patientId:id,shareCode:`CM-${Math.floor(100000+Math.random()*900000)}`};d.users.push(u);d.patients.push({id,name:u.name});d.medications[id]=seed();save(d);localStorage.setItem(SESSION,id);onLogin(u)}else{const u=d.users.find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===pass);if(!u)return setErr('E-mail ou senha inválidos.');localStorage.setItem(SESSION,u.id);onLogin(u)}}return <div className="auth"><div className="authIcon"><Pill size={40}/></div><h1>Controle de Medicamentos</h1><p>Organize seus horários e conte com alguém de confiança para acompanhar você.</p>{reg&&<input placeholder="Nome completo" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="E-mail" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Senha" type="password" value={pass} onChange={e=>setPass(e.target.value)}/>{err&&<div className="error">{err}</div>}<button onClick={submit}>{reg?'Criar conta':'Entrar'}</button><button className="ghost" onClick={()=>{setReg(!reg);setErr('')}}>{reg?'Já tenho uma conta':'Criar uma conta'}</button><div className="demo"><b>Contas de teste</b><br/>Paciente: paciente@demo.local / demo123<br/>Acompanhante: acompanhante@demo.local / demo123</div></div>}
function Onboarding({user,onDone}:{user:User;onDone:(u:User)=>void}){const[role,setRole]=useState<Role>(user.role),[code,setCode]=useState(''),[err,setErr]=useState('');function finish(){const raw=localStorage.getItem(KEY);if(!raw)return;const d:Store=JSON.parse(raw),u=d.users.find(a=>a.id===user.id);if(!u)return;if(role==='caregiver'){const p=d.users.find(a=>a.role==='patient'&&a.shareCode?.toUpperCase()===code.trim().toUpperCase());if(!p)return setErr('Código de compartilhamento não encontrado.');u.patientId=p.patientId||p.id;u.shareCode=null}else{u.patientId=u.patientId||u.id;u.shareCode=u.shareCode||`CM-${Math.floor(100000+Math.random()*900000)}`}u.role=role;u.onboardingCompleted=true;save(d);onDone({...u})}return <div className="auth onboarding"><div className="authIcon"><Users size={40}/></div><h1>Como você vai usar?</h1><p>Escolha o perfil que melhor descreve como você vai usar o aplicativo.</p><button className={`roleBtn ${role==='patient'?'selected':''}`} onClick={()=>setRole('patient')}><Pill size={24}/><span><b>Sou paciente</b><small>Organizar e registrar meus medicamentos.</small></span></button><button className={`roleBtn ${role==='caregiver'?'selected':''}`} onClick={()=>setRole('caregiver')}><Users size={24}/><span><b>Acompanhar familiar</b><small>Ver horários e registrar quando administrar.</small></span></button>{role==='caregiver'&&<input placeholder="Código do paciente" value={code} onChange={e=>setCode(e.target.value)}/>} {err&&<div className="error">{err}</div>}<button onClick={finish}>Continuar</button></div>}
function App(){const[data,setData]=useState<Store|null>(null),[user,setUser]=useState<User|null>(null),[tab,setTab]=useState('home'),[now,setNow]=useState(Date.now()),[editing,setEditing]=useState<Med|null>(null),[manual,setManual]=useState<Med|null>(null),[alarm,setAlarm]=useState<{med:Med;t:number}|null>(null),[confirmation,setConfirmation]=useState<{med:Med;kind:'used'|'administered';at:number;scheduled:number}|null>(null),[filter,setFilter]=useState('7'),[snooze,setSnooze]=useState<number|null>(null);
useEffect(()=>{load().then(d=>{setData(d);const sid=localStorage.getItem(SESSION);if(sid)setUser(d.users.find(u=>u.id===sid)||null)})},[]);useEffect(()=>{const i=setInterval(()=>setNow(Date.now()),1000),refresh=()=>load().then(setData);window.addEventListener('storage',refresh);let c:BroadcastChannel|undefined;try{c=new BroadcastChannel(CHANNEL);c.onmessage=refresh}catch{}return()=>{clearInterval(i);window.removeEventListener('storage',refresh);c?.close()}},[]);
const patientId=user?.patientId||user?.id||'',patient=data?.patients.find(p=>p.id===patientId),meds=data?.medications[patientId]||[],events=data?.events.filter(e=>e.patientId===patientId)||[];
const schedule=useMemo(()=>meds.map(m=>({m,t:pendingDose(m,meds,events)})).filter(x=>x.t!==null).sort((a,b)=>a.t!-b.t!),[meds,events]);
const overdue=schedule.filter(x=>x.t!<=now);const activePending=overdue[0]||null;const nextFuture=schedule.find(x=>x.t!>now)||null;
useEffect(()=>{if(!data||alarm||confirmation)return;const candidates=meds.map(m=>({m,t:pendingDose(m,meds,events)})).filter(x=>x.t!==null&&x.t!<=now&&!events.some(e=>e.medId===x.m.id&&e.scheduledAt&&Math.abs(Date.parse(e.scheduledAt)-x.t!)<1000)&&(!snooze||snooze<=now));const u=candidates.sort((a,b)=>a.t!-b.t!)[0];if(u?.t){setAlarm({med:u.m,t:u.t});if(data.settings.sound)alarmSound();if(data.settings.notifications&&'Notification'in window&&Notification.permission==='granted')new Notification('🔔 Hora do medicamento',{body:`Dose pendente: ${u.m.name}`})}},[now,meds,events,data,alarm,confirmation,snooze]);
if(!data)return <div className="loading"><div className="authIcon"><Pill size={38}/></div>Carregando...</div>;if(!user)return <Auth onLogin={setUser}/>;if(!user.onboardingCompleted)return <Onboarding user={user} onDone={setUser}/>;
const update=(fn:(x:Store)=>void)=>{const x=structuredClone(data);fn(x);save(x);setData(x);const u=x.users.find(a=>a.id===user.id);if(u)setUser({...u})};
const start=(m:Med,when=new Date())=>update(x=>{const z=x.medications[patientId]?.find(a=>a.id===m.id);if(z){z.start=when.toISOString();z.paused=false}});
const record=(m:Med,kind:'used'|'administered',when=new Date(),scheduledOverride?:number)=>{const scheduled=scheduledOverride??pendingDose(m,meds,events);if(scheduled===null)return;if(events.some(e=>e.medId===m.id&&e.scheduledAt&&Math.abs(Date.parse(e.scheduledAt)-scheduled)<1000))return;update(x=>x.events.push({id:uid(),patientId,medId:m.id,medName:m.name,at:when.toISOString(),by:kind==='administered'?user.name:'Paciente',kind,scheduledAt:new Date(scheduled).toISOString()}));setAlarm(null);setSnooze(null);setConfirmation({med:m,kind,at:when.getTime(),scheduled})};
const remove=(m:Med)=>{if(meds.some(a=>a.relatedId===m.id))return alert('Este medicamento está relacionado a outro. Edite a relação antes de excluir.');if(confirm(`Tem certeza que deseja excluir ${m.name}?`))update(x=>x.medications[patientId]=x.medications[patientId].filter(a=>a.id!==m.id));};
const filtered=events.filter(e=>{if(filter==='all')return true;const t=new Date(now);t.setHours(0,0,0,0);const d=new Date(e.at);if(filter==='today')return d>=t;if(filter==='yesterday'){const y=new Date(t);y.setDate(y.getDate()-1);return d>=y&&d<t}return now-Date.parse(e.at)<=Number(filter)*86400000});
const snoozeFor=(minutes:number)=>{setAlarm(null);setSnooze(Date.now()+minutes*60000)};
const status=(t:number)=>t<=now?'overdue':t-now<30*60000?'soon':'future';
return <div className="app"><header><div className="brand"><div className="brandPill"><Pill size={25}/></div><div><small>CONTROLE DE</small><h1>Medicamentos</h1><span className="who"><UserRound size={13} style={{verticalAlign:'-2px'}}/> {user.role==='caregiver'?'Acompanhando':'Paciente'}: {patient?.name||user.name}</span></div></div><button className="exit" onClick={()=>{localStorage.removeItem(SESSION);setUser(null)}}>Sair</button></header>
{alarm&&<div className="alarm"><button className="closeAlarm" onClick={()=>setAlarm(null)}><X size={25}/></button><div className="alarmIcon"><AlertTriangle size={55}/></div><div className="eyebrow">HORA DO MEDICAMENTO!</div><h2>DOSE PENDENTE</h2><div className="alarmMed">{alarm.med.name}</div><div className="alarmInfo"><span>Deveria ter sido às</span><strong>{clock(alarm.t)}</strong><span>Atrasado há</span><strong>{remain(alarm.t,now).replace('Atrasado ','')}</strong></div><button className="confirmBtn" onClick={()=>record(alarm.med,user.role==='caregiver'?'administered':'used',new Date(),alarm.t)}><Check size={22}/>{user.role==='caregiver'?'CONFIRMAR QUE FOI ADMINISTRADO':'CONFIRMAR QUE FOI USADO'}</button><div className="snooze"><button onClick={()=>snoozeFor(5)}><Clock3 size={18}/> ADIAR 5 MIN</button><button onClick={()=>snoozeFor(10)}><Clock3 size={18}/> ADIAR 10 MIN</button></div></div>}
{confirmation&&<div className="confirmation"><div className="checkCircle"><Check size={64}/></div><div className="eyebrow">CONFIRMAÇÃO CONCLUÍDA</div><h2>Medicamento confirmado!</h2><p className="confirmedName">{confirmation.med.name}</p><div className="confirmCard"><div><span>Previsto para</span><strong>{clock(confirmation.scheduled)}</strong></div><div><span>Confirmado às</span><strong>{clock(confirmation.at)}</strong></div></div><div className="nextAfter"><span>Próximo medicamento</span><b>{(meds.find(m=>pendingDose(m,meds,events)!>confirmation.at&&m.id!==confirmation.med.id)||schedule.find(x=>x.m.id!==confirmation.med.id&&x.t!>confirmation.at)?.m)?.name||'A definir'}</b><strong>{(()=>{const n=schedule.filter(x=>x.m.id!==confirmation.med.id&&x.t!>confirmation.at).sort((a,b)=>a.t!-b.t!)[0];return n?`${clock(n.t!)} · ${remain(n.t!,now)}`:''})()}</strong></div><button className="continue" onClick={()=>setConfirmation(null)}>CONTINUAR</button></div>}
{tab==='home'&&<main>{activePending?<section className="hero overdue"><div className="heroTop"><span><AlertTriangle size={18}/> DOSE PENDENTE</span><b>Muito atrasado</b></div><h2>{activePending.m.name}</h2><div style={{fontSize:14,fontWeight:700,opacity:.9}}>Deveria ter sido às</div><div className="heroTime"><Clock3 size={34}/>{clock(activePending.t!)}</div><div className="overdueText">🔴 {remain(activePending.t!,now)}</div><p>Ainda não foi confirmado</p><button className="confirmBtn" style={{marginTop:16,width:'100%'}} onClick={()=>setAlarm({med:activePending.m,t:activePending.t!})}><Check size={20}/> CONFIRMAR QUE FOI USADO</button></section>:<section className="hero"><div className="heroTop"><span><CalendarClock size={18}/> PRÓXIMO MEDICAMENTO</span><b>Programado</b></div><h2>{nextFuture?.m.name||'Nenhum programado'}</h2><div className="heroTime"><Clock3 size={34}/>{nextFuture?clock(nextFuture.t!):'—'}</div><strong>{nextFuture?remain(nextFuture.t!,now):'Defina o primeiro horário'}</strong><p>Você será alertado quando chegar a hora.</p></section>}
<h3 className="sectionTitle"><ClipboardList size={21}/> {activePending?'Outros medicamentos':'Próximos horários'}</h3>{schedule.filter(x=>activePending?x.m.id!==activePending.m.id:true).slice(0,8).map(x=><div className={`scheduleCard ${status(x.t!)}`} key={x.m.id}><div className="scheduleIcon"><Clock3 size={22}/></div><div className="scheduleMain"><b>{x.m.name}</b><span>{clock(x.t!)} · {remain(x.t!,now)}</span></div>{status(x.t!)==='soon'&&<span className="badge">CHEGANDO</span>}<ChevronRight className="chev" size={20}/></div>)}{!schedule.length&&<div className="empty"><Clock3 size={27}/><b>Nenhum horário programado</b><span>Defina o primeiro horário dos seus medicamentos.</span></div>}
<div className="shareCard"><div className="shareIcon"><Users size={23}/></div><div><b>Acompanhamento familiar</b>{user.role==='patient'?<><span>Compartilhe este código com seus familiares para que possam te acompanhar.</span><strong>{user.shareCode}</strong></>:<span>Você está acompanhando <b>{patient?.name}</b>. As administrações ficam registradas no histórico.</span>}</div>{user.role==='patient'&&<button className="ghost" onClick={()=>navigator.clipboard?.writeText(user.shareCode||'')}><Copy size={18}/></button>}</div></main>}
{tab==='meds'&&<main><div className="pageTitle"><div><small>SEUS MEDICAMENTOS</small><h2>Medicamentos</h2></div><button onClick={()=>setEditing({id:uid(),name:'',type:'Colírio',interval:1,unit:'hour',start:null,paused:false,relatedId:null,offset:0,note:''})}><Pill size={18}/> Adicionar</button></div>{meds.map(m=>{const n=pendingDose(m,meds,events);return <div className="medCard" key={m.id}><div className="medContent"><div className="medIcon"><Pill size={24}/></div><div><b>{m.name}</b><span>{m.type} · {m.interval}{m.unit==='hour'?'h':m.unit==='min'?' min':' dias'}</span><span>{m.paused?'⏸️ Pausado':m.start?'🟢 Ativo':'🕐 Aguardando primeiro horário'}</span></div>{n&&<span className="badge">{clock(n)}</span>}</div>{m.relatedId&&<span className="note">🔗 Relacionado: {meds.find(x=>x.id===m.relatedId)?.name||'removido'} +{m.offset} min</span>}{m.note&&<p className="note">{m.note}</p>}<div className="medActions">{!m.start&&<button onClick={()=>start(m)}><Play size={16}/> Começar agora</button>}{!m.start&&<button className="ghost" onClick={()=>setManual(m)}><Clock3 size={16}/> Definir horário</button>}{m.start&&<button className="ghost" onClick={()=>setManual(m)}><Clock3 size={16}/> Alterar horário</button>}{m.start&&<button onClick={()=>record(m,user.role==='caregiver'?'administered':'used')}><Check size={16}/> {user.role==='caregiver'?'Administrar':'Registrar uso'}</button>}<button className="ghost" onClick={()=>update(x=>{const z=x.medications[patientId].find(a=>a.id===m.id);if(z)z.paused=!z.paused})}>{m.paused?<Play size={16}/>:<Pause size={16}/>} {m.paused?'Retomar':'Pausar'}</button><button className="ghost" onClick={()=>setEditing({...m})}><PenLine size={16}/> Editar</button><button className="danger" onClick={()=>remove(m)}><Trash2 size={16}/> Excluir</button></div></div>})}</main>}
{tab==='history'&&<main><div className="pageTitle"><div><small>REGISTROS</small><h2>Histórico</h2></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="today">Hoje</option><option value="yesterday">Ontem</option><option value="7">7 dias</option><option value="30">30 dias</option><option value="all">Tudo</option></select></div>{filtered.slice().reverse().map(e=>{const name=e.medName||meds.find(m=>m.id===e.medId)?.name||'Medicamento removido';const scheduled=e.scheduledAt?Date.parse(e.scheduledAt):null;const taken=Date.parse(e.at);const delay=scheduled!==null?taken-scheduled:0;return <div className="historyCard" key={e.id}><div className="historyIcon"><Check size={21}/></div><div><b>{name}</b><span>{e.kind==='administered'?'💊 Administrado':'✅ Usado'} por {e.by}</span><small>{date(taken)} às {clock(taken)}{scheduled!==null?` · Previsto ${clock(scheduled)}`:''}{delay>0?` · ${Math.floor(delay/60000)} min de atraso`:''}</small></div></div>})}{!filtered.length&&<div className="empty"><ClipboardList size={27}/><b>Nenhum registro neste período</b></div>}</main>}
{tab==='settings'&&<main><div className="pageTitle"><div><small>APP</small><h2>Configurações</h2></div></div><div className="settingsCard"><button onClick={async()=>{if(!('Notification'in window))return alert('Notificações não são suportadas neste navegador.');const p=await Notification.requestPermission();update(x=>x.settings.notifications=p==='granted');alert(p==='granted'?'Notificações ativadas.':'Permissão não concedida.')} }><Bell size={19}/> Ativar notificações</button><button onClick={()=>{alarmSound();alert('Alarme testado.')}}><Volume2 size={19}/> Testar alarme</button><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='controle_medicamentos_backup.json';a.click()}}><Download size={19}/> Exportar backup</button><label className="filebtn"><Upload size={18}/> Importar backup<input type="file" accept="application/json" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));save(x);setData(x);alert('Dados importados com sucesso.')}catch{alert('JSON inválido.')}};r.readAsText(f)}}/></label><button className="danger" onClick={()=>{if(confirm('Limpar o histórico deste paciente?'))update(x=>x.events=x.events.filter(e=>e.patientId!==patientId))}}><Trash2 size={19}/> Limpar histórico</button><p>🟢 Dados locais: JSONs separados são a fonte inicial. localStorage + BroadcastChannel sincronizam abas/janelas do mesmo navegador. Para celulares diferentes é necessário backend.</p><p>⚠️ O aplicativo organiza horários e registros. Não substitui orientação médica.</p></div></main>}
<nav><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><House size={22}/><span>Início</span></button><button className={tab==='meds'?'active':''} onClick={()=>setTab('meds')}><Pill size={22}/><span>Medicamentos</span></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><ClipboardList size={22}/><span>Histórico</span></button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings size={22}/><span>Configurações</span></button></nav>
{editing&&<MedModal med={editing} meds={meds} onClose={()=>setEditing(null)} onSave={m=>{update(x=>{const a=x.medications[patientId]||[],i=a.findIndex(z=>z.id===m.id);if(i>=0)a[i]=m;else a.push(m)});setEditing(null)}}/>}{manual&&<ManualModal med={manual} onClose={()=>setManual(null)} onSave={(d,t)=>{start(manual,new Date(`${d}T${t}`));setManual(null)}}/>}</div>}
function MedModal({med,meds,onClose,onSave}:{med:Med;meds:Med[];onClose:()=>void;onSave:(m:Med)=>void}){const[m,setM]=useState({...med}),[d,setD]=useState(m.start?new Date(m.start).toISOString().slice(0,10):''),[t,setT]=useState(m.start?new Date(m.start).toTimeString().slice(0,5):'');return <div className="modal"><div className="modalbox"><button className="modalClose" onClick={onClose}><X size={20}/></button><small>CONFIGURAÇÃO</small><h2>{med.name?'Editar medicamento':'Adicionar medicamento'}</h2><label>Nome</label><input placeholder="Nome do medicamento" value={m.name} onChange={e=>setM({...m,name:e.target.value})}/><label>Tipo</label><select value={m.type} onChange={e=>setM({...m,type:e.target.value})}>{['Comprimido','Cápsula','Colírio','Gotas','Pomada','Injeção','Vitamina','Outro'].map(x=><option key={x}>{x}</option>)}</select><div className="grid2"><div><label>Intervalo</label><input type="number" min="1" value={m.interval} onChange={e=>setM({...m,interval:Math.max(1,Number(e.target.value))})}/></div><div><label>Unidade</label><select value={m.unit} onChange={e=>setM({...m,unit:e.target.value as Unit})}><option value="min">Minutos</option><option value="hour">Horas</option><option value="day">Dias</option></select></div></div><label>Primeiro horário</label><div className="grid2"><input type="date" value={d} onChange={e=>setD(e.target.value)}/><input type="time" value={t} onChange={e=>setT(e.target.value)}/></div><button className="ghost full" onClick={()=>{setD('');setT('');setM({...m,start:null})}}><Clock3 size={17}/> Aguardar para iniciar</button><label>Medicamento relacionado</label><select value={m.relatedId||''} onChange={e=>setM({...m,relatedId:e.target.value||null})}><option value="">Nenhum</option>{meds.filter(x=>x.id!==m.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>{m.relatedId&&<input type="number" min="0" placeholder="Atraso após relacionado (minutos)" value={m.offset} onChange={e=>setM({...m,offset:Math.max(0,Number(e.target.value))})}/>}<textarea placeholder="Observação" value={m.note} onChange={e=>setM({...m,note:e.target.value})}/><div className="actions"><button onClick={()=>m.name.trim()?onSave({...m,start:d&&t?new Date(`${d}T${t}`).toISOString():null}):alert('Informe o nome.')}>Salvar medicamento</button><button className="ghost" onClick={onClose}>Cancelar</button></div></div></div>}
function ManualModal({med,onClose,onSave}:{med:Med;onClose:()=>void;onSave:(d:string,t:string)=>void}){const[d,setD]=useState(med.start?new Date(med.start).toISOString().slice(0,10):new Date().toISOString().slice(0,10)),[t,setT]=useState(med.start?new Date(med.start).toTimeString().slice(0,5):new Date().toTimeString().slice(0,5));return <div className="modal"><div className="modalbox"><button className="modalClose" onClick={onClose}><X size={20}/></button><small>HORÁRIO</small><h2>Definir primeiro horário</h2><p>{med.name}</p><label>Data</label><input type="date" value={d} onChange={e=>setD(e.target.value)}/><label>Horário</label><input type="time" value={t} onChange={e=>setT(e.target.value)}/><button className="full" onClick={()=>onSave(d,t)}>Salvar horário</button></div></div>}
export default App;
